/**
 * 2D export: SVG and DXF (spec feature 10).
 *
 * Both take the contour lists produced by a 2D render. SVG's Y axis points
 * down, so contours are flipped; DXF shares OpenSCAD's Y-up convention and is
 * written as-is.
 */

export type Contour = [number, number][];

export interface Vector2DPart {
  contours: Contour[];
  color?: [number, number, number, number];
}

export interface Vector2DOptions {
  /** Unit suffix on the SVG `width`/`height`; models are millimetres by convention. */
  unit?: string;
  /** Margin in model units added around the content. */
  margin?: number;
  generator?: string;
}

interface Bounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

function boundsOf(parts: Vector2DPart[]): Bounds {
  const b: Bounds = { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };
  for (const part of parts) {
    for (const contour of part.contours) {
      for (const [x, y] of contour) {
        b.minX = Math.min(b.minX, x);
        b.minY = Math.min(b.minY, y);
        b.maxX = Math.max(b.maxX, x);
        b.maxY = Math.max(b.maxY, y);
      }
    }
  }
  if (!Number.isFinite(b.minX)) return { minX: 0, minY: 0, maxX: 0, maxY: 0 };
  return b;
}

export function exportSVG(parts: Vector2DPart[], options: Vector2DOptions = {}): string {
  const margin = options.margin ?? 1;
  const unit = options.unit ?? 'mm';
  const b = boundsOf(parts);
  const width = b.maxX - b.minX + margin * 2;
  const height = b.maxY - b.minY + margin * 2;

  const out: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<svg xmlns="http://www.w3.org/2000/svg" width="${f(width)}${unit}" height="${f(height)}${unit}" ` +
      `viewBox="0 0 ${f(width)} ${f(height)}">`,
    `  <!-- Generated by ${escapeXml(options.generator ?? 'BetterSCAD')} -->`,
  ];

  for (const part of parts) {
    // Even-odd fill reproduces holes the same way the 2D kernel understands them.
    const fill = part.color ? rgbString(part.color) : '#000000';
    const opacity = part.color ? part.color[3] : 1;
    const d = part.contours
      .map((contour) => {
        if (contour.length < 3) return '';
        const points = contour.map(
          ([x, y]) => `${f(x - b.minX + margin)},${f(height - (y - b.minY + margin))}`,
        );
        return `M ${points.join(' L ')} Z`;
      })
      .filter(Boolean)
      .join(' ');
    if (d) {
      out.push(
        `  <path d="${d}" fill="${fill}" fill-opacity="${f(opacity)}" fill-rule="evenodd" stroke="none" />`,
      );
    }
  }

  out.push('</svg>', '');
  return out.join('\n');
}

/**
 * Minimal DXF R12, which is the most widely readable revision.
 *
 * Each contour becomes a closed LWPOLYLINE on layer `0`.
 */
export function exportDXF(parts: Vector2DPart[], options: Vector2DOptions = {}): string {
  const out: string[] = [];
  const pair = (code: number, value: string | number): void => {
    out.push(String(code), String(value));
  };

  pair(0, 'SECTION');
  pair(2, 'HEADER');
  pair(9, '$ACADVER');
  pair(1, 'AC1009');
  pair(0, 'ENDSEC');

  pair(0, 'SECTION');
  pair(2, 'ENTITIES');

  for (const part of parts) {
    for (const contour of part.contours) {
      if (contour.length < 3) continue;
      pair(0, 'LWPOLYLINE');
      pair(8, '0'); // layer
      pair(100, 'AcDbEntity');
      pair(100, 'AcDbPolyline');
      pair(90, contour.length); // vertex count
      pair(70, 1); // closed
      for (const [x, y] of contour) {
        pair(10, f(x));
        pair(20, f(y));
      }
    }
  }

  pair(0, 'ENDSEC');
  pair(0, 'EOF');
  void options;
  return `${out.join('\n')}\n`;
}

function f(n: number): string {
  if (!Number.isFinite(n)) return '0';
  if (Number.isInteger(n)) return String(n);
  return Number.parseFloat(n.toFixed(6)).toString();
}

function rgbString(color: [number, number, number, number]): string {
  const byte = (c: number): number => Math.round(Math.min(1, Math.max(0, c)) * 255);
  return `rgb(${byte(color[0])},${byte(color[1])},${byte(color[2])})`;
}

function escapeXml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
